version: 2.1

jobs:
  run-tests:
    docker:
      - image: circleci/openjdk:17-jdk
    steps:
      - checkout
      - run: chmod +x mvnw ./mvnw dependency:go-offline
      - run: chmod +x mvnw ./mvnw test

workflows:
  run-tests-workflow:
    jobs:
      - run-tests:
          filters:
            branches:
              only:
                - dev
                - qa