version: 2.1

jobs:
  run-tests:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          ./mvnw test

workflows:
  run-tests-workflow:
    jobs:
      - run-tests:
          filters:
            branches:
              only:
                - dev
                - qa
