version: 2.1

jobs:
  run-tests:
    docker:
      - image: cimg/openjdk:17.0.3
    steps:
      - checkout
      - run: chmod +x mvnw
      - run: ./mvnw -DargLine="-Dspring.profiles.active=test" test

workflows:
  run-tests-workflow:
    jobs:
      - run-tests:
          filters:
            branches:
              only:
                - dev
                - qa